apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlops-developer-role
  namespace: mlops-project
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["deployments", "replicasets", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log", "pods/exec"]
  verbs: ["get", "list", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-developer
  namespace: mlops-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlops-developer-binding
  namespace: mlops-project
subjects:
- kind: ServiceAccount
  name: mlops-developer
  namespace: mlops-project
roleRef:
  kind: Role
  name: mlops-developer-role
  apiGroup: rbac.authorization.k8s.io