- name: Deploy LiverCareApp to Kubernetes using Ansible
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    kubeconfig_path: "{{ kubeconfig_path | default('/tmp/kubeconfig') }}"  # Use default path if not passed

  tasks:
    - name: Write kubeconfig to temporary location
      copy:
        dest: "{{ kubeconfig_path }}"
        content: |
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: https://192.168.49.2:8443
              insecure-skip-tls-verify: true
            name: k8s-cluster
          contexts:
          - context:
              cluster: k8s-cluster
              user: jenkins
            name: jenkins-context
          current-context: jenkins-context
          users:
          - name: jenkins
            user:
              token: "{{ lookup('env', 'K8S_TOKEN') }}"
      no_log: true

    - name: Apply Kubernetes manifests
      shell: KUBECONFIG={{ kubeconfig_path }} kubectl apply -f {{ playbook_dir }}/../k8s-manifests/
