---
- name: Deploy LiverCareApp to Kubernetes using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    kubeconfig_path: "{{ kubeconfig_path | default('./.kube/config') }}"
    manifests_dir: "{{ playbook_dir }}/../k8s-manifests"

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  tasks:
    - name: Verify kubeconfig file exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_file

    - name: Fail if kubeconfig is missing
      fail:
        msg: "Kubeconfig not found at {{ kubeconfig_path }}"
      when: not kubeconfig_file.stat.exists

    - name: Verify manifests directory exists
      stat:
        path: "{{ manifests_dir }}"
      register: manifests_dir_stat

    - name: Fail if manifests directory is missing
      fail:
        msg: "Kubernetes manifests directory not found at {{ manifests_dir }}"
      when: not manifests_dir_stat.stat.exists

    - name: Validate Kubernetes connection
      command: "kubectl cluster-info"
      register: cluster_info
      changed_when: false
      ignore_errors: yes

    - name: Fail if cannot connect to cluster
      fail:
        msg: "Failed to connect to Kubernetes cluster. Error: {{ cluster_info.stderr }}"
      when: cluster_info.rc != 0

    - name: Apply Kubernetes Manifests
      command: "kubectl apply -f {{ manifests_dir }}"
      register: apply_result

    - name: Verify deployment success
      fail:
        msg: "Failed to apply manifests. Error: {{ apply_result.stderr }}"
      when: apply_result.rc != 0

    - name: Show deployment results
      debug:
        msg: "Successfully applied Kubernetes manifests. Output: {{ apply_result.stdout }}"
      when: apply_result.rc == 0