---
- name: Deploy LiverCareApp to Kubernetes using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    kubeconfig_path: "{{ kubeconfig_path | default('./.kube/config') }}"

  tasks:

    - name: Verify kubeconfig file exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_file

    - name: Fail if kubeconfig is missing
      fail:
        msg: "Kubeconfig not found at {{ kubeconfig_path }}"
      when: not kubeconfig_file.stat.exists

    - name: Apply Kubernetes Manifests
      shell: KUBECONFIG="{{ kubeconfig_path }}" kubectl apply -f {{ playbook_dir }}/../k8s-manifests/
