apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mlops-project
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: prabhav49/frontend-app:latest
        imagePullPolicy: Always  # Force pull of new images
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: "http://backend-service:8000"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20