apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-rolebinding
subjects:
- kind: ServiceAccount
  name: jenkins-service-account
  namespace: default  # Ensure this matches the namespace of the service account
roleRef:
  kind: ClusterRole
  name: jenkins-role  # This references the ClusterRole we created
  apiGroup: rbac.authorization.k8s.io
