apiVersion: v1
kind: Service
metadata:
  name: model-retrain-service
  namespace: mlops-project
  labels:
    app: model-retrain
spec:
  selector:
    app: model-retrain
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP